"""entry addition

Revision ID: ad660d5d3961
Revises: ccc821b2001d
Create Date: 2020-10-08 22:23:38.774962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad660d5d3961'
down_revision = 'ccc821b2001d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('choose_activity', sa.String(length=90), nullable=True))
    op.add_column('post', sa.Column('choose_cooldown', sa.String(length=90), nullable=True))
    op.add_column('post', sa.Column('choose_effort', sa.String(length=90), nullable=True))
    op.add_column('post', sa.Column('choose_title', sa.String(length=90), nullable=True))
    op.add_column('post', sa.Column('choose_warmedup', sa.String(length=90), nullable=True))
    op.add_column('post', sa.Column('gps_data', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'gps_data')
    op.drop_column('post', 'choose_warmedup')
    op.drop_column('post', 'choose_title')
    op.drop_column('post', 'choose_effort')
    op.drop_column('post', 'choose_cooldown')
    op.drop_column('post', 'choose_activity')
    # ### end Alembic commands ###
